{"start": 1607410303434, "befores": [{"status": "broken", "start": 1607410303434, "stop": 1607410303434, "name": "set_up", "statusDetails": {"message": "IOError: [Errno 2] No such file or directory: 'src/utilities/config.txt'\n", "trace": "  File \"/usr/local/lib/python2.7/dist-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python2.7/dist-packages/_pytest/fixtures.py\", line 936, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/_pytest/fixtures.py\", line 795, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/home/orion92/catkin_ws/src/atg/src/tests/pick_test.py\", line 44, in set_up\n    self.config = Configuration()\n  File \"/home/orion92/catkin_ws/src/atg/src/tests/file_reader/file_reader.py\", line 32, in __init__\n    with open(\"src/utilities/config.txt\",mode='r') as file:\n"}}], "stop": 1607410303449, "uuid": "9ae66a09-ad59-4337-abfb-1d88bfc6b9b9", "children": ["df5a6e81-f9b6-44a3-b14a-90dc3a1e76ea"]}