{"start": 1607410303419, "befores": [{"status": "broken", "start": 1607410303419, "stop": 1607410303419, "name": "set_up", "statusDetails": {"message": "IOError: [Errno 2] No such file or directory: 'src/utilities/config.txt'\n", "trace": "  File \"/usr/local/lib/python2.7/dist-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python2.7/dist-packages/_pytest/fixtures.py\", line 936, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/_pytest/fixtures.py\", line 795, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/home/orion92/catkin_ws/src/atg/src/tests/pick_test.py\", line 44, in set_up\n    self.config = Configuration()\n  File \"/home/orion92/catkin_ws/src/atg/src/tests/file_reader/file_reader.py\", line 32, in __init__\n    with open(\"src/utilities/config.txt\",mode='r') as file:\n"}}], "stop": 1607410303430, "uuid": "38836912-149c-4377-93c9-028bb288fdc3", "children": ["8e1e52aa-360c-48fb-8b5e-c6ecb21f6ff3"]}